<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <?= $this->headTitle('Motion')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ?>
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico']) // favicon à modifier
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>
        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/script.js'))
            ->prependFile($this->basePath('js/lyd_slider.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <body>
        <div id="page">
            <header>
                <div class="wrapper">
                    <div class="left">                    
                        <h1>
                            <img src="<?= $this->basePath('img/logo.png') ?>" alt="logo.png"/><span class="line1">Motion</span><br />
                            <span class="line2">A single Page Template</span>
                        </h1>
                    </div>
                    <ul class="right">
                        <?php 
                            foreach ($menu as $m){
                        ?>
                        <li><a href="<?= $this->url($m) ?>"><?= $m ?></a></li>
      
                        <?php 
                            }
                        ?>

                    </ul>
                    <div class="clear"></div>
                </div>
                <img class="imgRight" src="<?= $this->basePath('img/header_right.png') ?>" alt="header_right.png"/>
            </header>
            <div class="pinkEffectBar"></div>


                <?= $this->content ?>


            <div class="wrapper">
                <footer>
                    <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
                </footer>
            </div>
            <?= $this->inlineScript() ?>
            <!--<script type="text/javascript" src="js/script.js"></script>-->
        </body>
        </div>
</html>