<div class="slider">
    <div class="wrapper">
        <h2>Welcome to Motion</h2>
        <p>Asmart & Creative Single Page Template</p>
        <div class="lydSlider">
            <img src="../img/slider-left.png" alt="left">
            <div class="container">
                <div class="bar">            
                    <div class="imgBox box1"><img src="../img/slider1.jpg" alt="1"></div>
                    <div class="imgBox box2"><img src="../img/slider2.jpg" alt="2"></div>
                    <div class="imgBox box3"><img src="../img/slider3.jpg" alt="3"></div>
                </div>            
            </div>
            <img src="../img/slider-right.png" alt="right">
        </div>
    </div>
</div>